### ISSUE TITLE
Problem setting initial values

### ISSUE THREAD

**Issue by bayd** [goedman/Stan.jl#39]
I can't find a way to set initial values for my sampler.

Stanmodel.jl Stanmodel type has `init` which I believe should act as the container for initial values
```
type Stanmodel
  name::String
  nchains::Int
  ...
  init::Init
  output::Output
  tmpdir::String
end
```
which is defined to be of type `Init`
```
type Init
  init::Int64
end
Init(;init::Number=2) = Init(init)
```
So it only accepts one integer.

In pystan one can give a dictionary in following manner:
```
init = {"theta1": 0.5, "theta2": 0.9}
```

I tried giving a dictionary, self-made Init type with the attributes corresponding to the parameter values I'd like to initialize but could not work around it.

**Comment by michael-prange** [comment]
I’m not an expert, but after a bit of trial and error I got the following to work. I suggest that the init argument should be greatly simplified in a future implementation.

Michael

prog = "parameters {
  simplex[2] z;
}
model {}"
model=Stanmodel(name="mymodel", model=prog, nchains=1, 
        init=Stan.Init(init=Dict{String, Any}[Dict("z" => [0.5; 0.5])]))
stan(model)

**Comment by goedman** [comment]
@bayd  Hi, this has come up a number of times over the last few months. The master version of Stan.jl has several examples and updates on this topic. Can you check with the latest master (Pkg.checkout*"Stan") ? There are also a few examples on this in BernoulliChris, BernoulliInitTheta and BernoulliScalar. Note that BernoulliChris requires the latest development version of CmdStan, there is a bug in CmdStan 2.14.0. Let me know if this helps.

Regards,
Rob

**Comment by goedman** [comment]
@michael-prange Hi Michael, yes, you're absolutely right.

Before tagging Stan.jl v"1.1.0" I had 3 items on my list of things to do:

1. Julia v"0.6" (but that also depends on Mamba and Gadfly)
2. Running Stan models from anywhere (I'm not sure why occasionally I see problems with that)
3. Fixing the initialization issues (e.g. items #34, #38 and now #39)

I've also wondered if anyone has used item #36?

Any feedback on these and other topics is appreciated!  E.g., do folks like the coupling with Mamba and Mamba graphics? How important is access to Stan functions on C++ level? Over the last year I have certainly seen more R focus in the Stan team, how important is that? Maybe after 2 years it's time to do major surgery on Stan.jl? I'm also pretty busy right now, so no promises, even if I could tackle some of these larger topics.

Regards,
Rob

**Comment by michael-prange** [comment]
Rob,

I’m not currently using the Mamba or Gadfly graphics. Once I have the samples, it is my practice to produce the graphics on my own in order to achieve publication quality results.

I’m not sure what you mean by “access to Stan functions on C++ level”. I would like to call C++ functions from Stan, but there is currently no Stan support for that. I’m forced to patch the hpp code to include such functions.

Thanks for creating and supporting Stan.jl. It has been a super time saver in my current research and constitutes my principal use of julia thus far.

Michael

**Comment by goedman** [comment]
Thank you Michael for your feedback.

 I meant access to functions that are compiled into the Stan library, these function can be used during either pre-processing,  sampling or post-processing of sampling results. Your use and functions added via the the Stan language are indeed different. R and Python have the ability to call these compiled-into-Stan functions.

Functions like you use and patch into the hpp code have not been high on my list (mainly because Julia has Klara and Mamba as alternative solutions where this is feasible).

I think it is better to open a separate issue about possible future directions of Stan.jl, so this discussion is not hidden under another issue.

I'll leave this issue open until I hear back from @bayd.

Regards,
Rob

**Comment by bayd** [comment]
Ok I found the examples from the github page. I did browse previously the examples provided by the package. It is clear now, thank you!

**Comment by goedman** [comment]
Thanks @bayd.

**Comment by michael-prange** [comment]
Rob,

I’ve not used Stan.jl for about six months and am now updating my codes to use the latest released version of Stan.jl. I had been using the init arg in Stanmodel, but noticed that it was being ignored. On checking stancode.jl, I noticed that the stan() only uses its own init arg, ignoring the one in Stanmodel. It seems to be that the init arg should be removed from the code and documentation for Stanmodel if it is no longer used.

Michael

**Comment by goedman** [comment]
Thank you Michael, I’ll look into that. Recently a bug was fixed where thinning took place twice, so I might have done something wrong there.

Are you working on Julia 0.6 or 0.7?

Best
Rob J Goedman

**Comment by michael-prange** [comment]
julia 0.6.2, the latest released version.

**Comment by goedman** [comment]
Thanks Michael,

You’re correct. It was even mentioned in the breaking changes section.

I’ll figure out how to take it along in an upcoming update, including a corresponding docs update.

Best,
Rob
