### ISSUE TITLE
Feature Enhancement: auto save posterior summaries

### ISSUE THREAD

**Issue by fisherc2** [goedman/Stan.jl#46]
Hi Rob-
Perhaps there is already a solution, but I could not figure out how to save either the Stan or Mamba posterior summaries. In either case, I was thinking it might be convenient to automatically save that along with the data and posterior sample files.

**Comment by goedman** [comment]
Hi Chris,

That definitely makes sense for cases when reprocessing the Stan generated files takes a long time. Let me have a look at it.

This weekend I'm still traveling but should be back in La Jolla next Tuesday.

Best,
Rob

**Comment by fisherc2** [comment]
Indeed, I have found myself in that very situation. Thanks for adding that feature. 

Best regards,

Chris

**Comment by goedman** [comment]
Hi Chris, haven't forgotten your request.

Turns out Mamba has build-in features for writing the output to a file (http://mambajl.readthedocs.io/en/latest/tutorial.html?highlight=write#file-i-o).

In Stan.jl I receive the CmdStan summary as a String, I need to add a function to store that string to a file in the  /tmp directory.

As a result of our trip this summer, we have decided to move (after 27 years CA!) to live part time in CO and part time in DC. This will definitely take many cycles, so I apologize in advance if I'm slow in responding until at least October.

**Comment by fisherc2** [comment]
Hi Rob-
Thanks for the update and no worries. It looks like the Mamba feature will hold me over.

Good luck with your new homes and have a safe trip!

**Comment by goedman** [comment]
I will close this issue for now in the hope the Mamba feature will suffice.

My **plan** is to refactor Stan.jl (_over the next year_) for Julia 1.0. During the refactor I will keep this request in mind.

**Comment by goedman** [comment]
Hi Chris,

Thanks for the update. I’ll keep this in mind. Hadn’t realized these different diagnostics!

Best,
Rob
