### ISSUE TITLE
confusing docstrings

### ISSUE THREAD

**Issue by kleinschmidt** [goedman/Stan.jl#50]
The [docstring for `stan()`](http://goedman.github.io/Stan.jl/latest/#stan()-1) says that the `data` and `ProjDir` arguments are required, but in the source they're defined as [optional positional arguments](https://docs.julialang.org/en/stable/manual/methods/#Note-on-Optional-and-keyword-Arguments-1).  Also, the way they're described is confusing since you don't call the method with the argument name (while you do for the keyword arguments, which are described similarly).

I think it would help a lot to have example syntax for all of them.  If I get time I'll open a PR but wanted to point this out here since it came up on slack.

**Comment by goedman** [comment]
Thank you for raising the issue here, as I’m not on slack. I’m certainly open to suggestions on how to improve the docs and/or method call.

As the call to stan() does not use multiple dispatch, this could be changed in a next major release.

Does the current set of examples help? E.g. Binormal is an example that does not need input data, all other examples do. Although it is possible to run from the current working directory, I think in most cases it is probably better to set it explicitly.

**Comment by goedman** [comment]
Thank you Dave for the PR. The PR made it much clearer what you were asking for and I felt it is a major improvement! Merging it was therefor a no-brainer. Please do not hesitate to suggest further updates, even minor ones.

**Comment by kleinschmidt** [comment]
My pleasure! Thanks for merging quickly.
